### ISSUE TITLE
Crash when attempting to add long sign arguments.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Mechanics#28]
1. Make a portal with the following sign as an opped user:
```
something

Network
{}
```

```java
[ERROR]: Could not pass event StargatePreCreatePortalEvent to StargateMechanics v0.1.0-ALPHA
java.lang.NoClassDefFoundError: net/minecraft/world/entity/player/EntityHuman
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at StargateMechanics-0.1.0-ALPHA.jar/org.sgrewritten.stargatemechanics.anvilgui.version.VersionMatcher.match(VersionMatcher.java:43) ~[StargateMechanics-0.1.0-ALPHA.jar:?]
        at StargateMechanics-0.1.0-ALPHA.jar/org.sgrewritten.stargatemechanics.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:42) ~[StargateMechanics-0.1.0-ALPHA.jar:?]
        at StargateMechanics-0.1.0-ALPHA.jar/org.sgrewritten.stargatemechanics.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:400) ~[StargateMechanics-0.1.0-ALPHA.jar:?]
        at StargateMechanics-0.1.0-ALPHA.jar/org.sgrewritten.stargatemechanics.listener.StargateEventListener.createPortal(StargateEventListener.java:151) ~[StargateMechanics-0.1.0-ALPHA.jar:?]
        at StargateMechanics-0.1.0-ALPHA.jar/org.sgrewritten.stargatemechanics.listener.StargateEventListener.onStargatePreCreatePortal(StargateEventListener.java:134) ~[StargateMechanics-0.1.0-ALPHA.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.listener.BlockEventListener.onSignChange(BlockEventListener.java:193) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.SignBlockEntity.setMessages(SignBlockEntity.java:226) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.world.level.block.entity.SignBlockEntity.lambda$updateSignText$4(SignBlockEntity.java:187) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.world.level.block.entity.SignBlockEntity.updateText(SignBlockEntity.java:201) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.world.level.block.entity.SignBlockEntity.updateSignText(SignBlockEntity.java:186) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3457) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$20(ServerGamePacketListenerImpl.java:3438) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.player.EntityHuman
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 47 more
```

**Comment by Thorinwasher** [comment]
Fixed in 514b358e8f34560599d635ebc09ff7c7a239ae47
