### ISSUE TITLE
Crash when creating N gates

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Mechanics#29]
```
Origin
Destination
Network
N
```

```java
[ERROR]: Could not pass event StargateSignFormatPortalEvent to StargateMechanics v0.1.0-ALPHA
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149) ~[?:?]
        at StargateMechanics-0.1.0-ALPHA.jar/org.sgrewritten.stargatemechanics.listener.StargateEventListener.onStargateSignFormatGateEvent(StargateEventListener.java:245) ~[StargateMechanics-0.1.0-ALPHA.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor66.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.gate.Gate$1.run(Gate.java:158) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.thread.task.StargateTask.runTask(StargateTask.java:101) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.thread.task.StargateRegionTask.lambda$runPopulatorTask$3(StargateRegionTask.java:60) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.thread.SynchronousPopulator.cycleQueue(SynchronousPopulator.java:91) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.thread.SynchronousPopulator.run(SynchronousPopulator.java:27) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at Stargate-1.0.0.16-NIGHTLY-3.jar/org.sgrewritten.stargate.thread.task.StargateBukkitRunnable.run(StargateBukkitRunnable.java:13) ~[Stargate-1.0.0.16-NIGHTLY-3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Latest paper, core, and addons on windows.

**Comment by Thorinwasher** [comment]
Probably fixed in b8d83351cdf83c96ab563833a29bdd9fc619c879

(line 245-247
